---
- hosts: mywebservers
  become: yes
  tasks:  
    - name: install httpd
      dnf:
         name: "{{webpack}}"
         state: present 
    #- name: start httpd
      #service:
        # name: "{{webpack}}"
        # state: Stopped
   