---
- hosts: mywebservers
  become: yes
  tasks:  
    - name: install httpd
      dnf:
         name: "{{webpack}}"
         state: present 
      when: ansible_os_family =="RedHat"
    
    - name: install apache2
      apt:
         name: "{{webpack}}"
         state: present  
      when: ansible_os_family =="Debian"

    - name: Start httpd/apache2
      service:
         name: "{{webpack}}"
         state: started