---
- hosts: mywebservers
  become: yes
  tasks:  
    - name: install httpd
      dnf:
         name: "{{webpack}}"
         state: absent 
    - name: start httpd
      service:
         name: "{{webpack}}"
         state: Stopped
   