---
- name: download Tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz
    dest: /home/harm/apache-tomcat-9.0.55.tar.gz
    force_basic_auth: yes
- name: Create opt folder
  file:
    path: /opt/tomcat
    state: directory
- name: extract
  command:
     cmd: tar -zvxf /home/harm/apache-tomcat-9.0.55.tar.gz -C /opt/tomcat --strip-components=1
     creates: /opt/tomcat