---
   -  name: create tomcat dir
      file:
           path: /opt/tomcat
           state: directory

   -  name: downlod tom tar file
      get_url:
           url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.26/bin/apache-tomcat-10.1.26.tar.gz
           dest: /opt/tomcat/apache-tomcat-8.5.100.tar.gz.conf
           force_basic_auth: yes

   -  name: extract
      command:
          cmd: tar -zvxf /opt/tomcat/apache-tomcat-8.5.100.tar.gz.conf
          creates: /opt/tomcat/LICENSE
         

