---
   -  name: create tomcat dir
      file:
           path: /opt/tomcat
           state: directory

   -  name: downlod tom tar file
      get_url:
           url: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/9.0.55/tomcat-9.0.55.tar.gz
           dest: /home/harm/tomcat/9.0.55/tomcat-9.0.55.tar.gz
           force_basic_auth: yes

   -  name: extract
      command:
          cmd: tar -zvxf /home/harm/tomcat/9.0.55/tomcat-9.0.55.tar.gz -C /opt/tomcat --strip-components=1
          creates: /opt/tomcat/LICENSE
         

