---
- name: permission start
  command:
       cmd: chmod +x /opt/tomcat/tomcat-9.0.55.tar/bin/startup.sh

- name: permission shut
  command:
       cmd: chmod +x /opt/tomcat/tomcat-9.0.55.tar/bin/shutdown.sh

      
- name: create tomcatup
  command:
       cmd: ln -s /opt/tomcat/tomcat-9.0.55.tar/bin/startup.sh /usr/local/bin/tomcatup
       creates: /usr/local/bin/tomcatup


- name: creates tomcatdown
  command:
       cmd: ln -s /opt/tomcat/tomcat-9.0.55.tar/bin/shutdown.sh /usr/local/bin/tomcatdown
       creates: /usr/local/bin/tomcatdown

- name: catup
  command:
       cmd: tomcatup