---
- name: create start
  file:
       path: /opt/tomcat/apache-tomcat-10.1.26/bin/startup.sh
       creates: /opt/tomcat/apache-tomcat-10.1.26/bin/startup.sh
- name: create shut
  file:
       path: /opt/tomcat/apache-tomcat-10.1.26/bin/shutdown.sh
       creates: opt/tomcat/apache-tomcat-10.1.26/bin/shutdown.sh

- name: permission start
  command:
       cmd: chmod +x /opt/tomcat/apache-tomcat-10.1.26/bin/startup.sh

- name: permission shut
  command:
       cmd: chmod +x /opt/tomcat/apache-tomcat-10.1.26/bin/shutdown.sh

      
- name: create tomcatup
  command:
       cmd: ln -s /opt/tomcat/apache-tomcat-10.1.26/bin/startup.sh /usr/local/bin/tomcatup
       creates: /usr/local/bin/tomcatup


- name: creates tomcatdown
  command:
       cmd: ln -s /opt/tomcat/apache-tomcat-10.1.26/bin/shutdown.sh /usr/local/bin/tomcatdown
       creates: /usr/local/bin/tomcatdown

- name: catup
  command:
       cmd: tomcatup