---
- name: download war file
  template:
     src: templates/msg.j2
     dest: /opt/tomcat/webapps/msg.j2
  
- name: down
  command:
       cmd: tomcatdown

- name: catup2
  command:
       cmd: tomcatup